name: Deploy to AWS (release)
on:
  push:
    branches:
      - "main"
permissions:
  id-token: write
  contents: read
jobs:
  build-and-deploy:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          buildkitd-flags: --debug
      - name: restore libavjs cache
        uses: actions/cache@v3
        with:
          key: libavjs-files--${{ hashFiles('libavjs/*') }}
          path: public/app/bundled/libavjs/
      - name: install packages
        run: npm install .
      - name: Build
        run: DOCKER="docker buildx" DOCKER_TMPDIR=/tmp make all
      - name: Set AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-east-1
          role-to-assume: arn:aws:iam::442430797903:role/behave-claude-apps-com-UploadRole-bcTUZbepmRpa
      - name: Deploy
        run: aws s3 sync --delete --exclude=beta/\* --content-encoding utf8 public s3://behave.claude-apps.com/website/
