name: Deploy to AWS (release)
on:
  push:
    release:
      types: [created]
    branches:
      - "main"
permissions:
  id-token: write
  contents: read
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true
      - name: Determine version number
        run: >
          set -e; echo "BEHAVE_VERSION=$(python determine_version_number.py)" >> $GITHUB_ENV
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          buildkitd-flags: --debug
      - name: restore libavjs cache
        uses: actions/cache@v3
        with:
          key: libavjs-files--${{ hashFiles('libav.js/*') }}
          path: public/app/bundled/
      - name: update cache timestamps
        # this will update the timestamps on the cache
        # this is necessary since the Dockerfile will always be newer (gets
        # checkout timestamp).
        # However because of the hash, cache only gets restored if the Dockerfile
        # is unchanged.
        run: make -t public/app/bundled/libavjs || true
      - name: Build
        run: DOCKER="docker buildx" BEHAVE_VERSION="$(echo "${BEHAVE_VERSION}" | sed 's/\$/$$/g')" DOCKER_TMPDIR=/tmp ENVIRONMENT=production make lint all
      - name: Upload artifacts
        uses: actions/upload-artifact@master
        with:
          name: built-app
          path: public
  deploy-beta:
      runs-on: ubuntu-22.04
      needs: build
      steps:
      - uses: actions/download-artifact@master
        name: Download artifact
        with:
          name: built-app
          path: public
      - name: Set AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-east-1
          role-to-assume: arn:aws:iam::442430797903:role/behave-claude-apps-com-UploadRole-bcTUZbepmRpa
      - name: Deploy to live
        run: aws s3 sync --delete --content-encoding utf8 public s3://behave.claude-apps.com/website/beta/main
